create table users(
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(30) DEFAULT 'student',
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE students(
    id SERIAL PRIMARY KEY ,
    USER_ID INTEGER REFERENCES USERS(ID) ON DELETE CASCADE,
    ENROLLMENT_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR(10),
    ADDRESS TEXT,
    DEPARTMENT VARCHAR(100),
    SEMESTER INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



